import type { ReactElement } from "react";
export interface PersistedPromptArtifact { readonly artifactId: string; readonly redacted: true; readonly nodeId: string; readonly modelAlias: string; readonly protocol: { readonly id: string; readonly version: string; readonly hash: string; readonly locked: true }; readonly overrides: { readonly before: string; readonly after: string }; readonly compiledPreview: string; readonly promptHash: string; readonly lint: readonly { readonly code: string; readonly severity: "warning" | "error"; readonly message: string }[]; readonly context: { readonly policy: string; readonly trust: "system" | "derived" | "untrusted"; readonly included: readonly string[]; readonly excluded: readonly string[]; readonly tokenEstimate: number | null; readonly estimateBasis: string | null }; readonly output: { readonly schema: string; readonly requiredFields: readonly string[]; readonly validationBehaviour: string; readonly structuredOutputTier: string; readonly tierDegradation: string | null }; readonly cacheHitRate: number | null }
export type PromptSelection = { readonly kind: "model"; readonly artifact: PersistedPromptArtifact | null } | { readonly kind: "deterministic"; readonly nodeId: string; readonly transformation: Readonly<Record<string, unknown>> };
export function PromptView({ selection }: { readonly selection: PromptSelection }): ReactElement { if (selection.kind === "deterministic") return <section aria-labelledby="transform-title"><h2 className="panel-title" id="transform-title">deterministic transformation</h2><pre>{JSON.stringify(selection.transformation, null, 2)}</pre><p className="state" data-state="verified">application transformation · no model prompt</p></section>; const artifact = selection.artifact; if (artifact === null) return <section><h2 className="panel-title">prompt · context · contract</h2><p className="state" data-state="unexamined">persisted prompt artifact unavailable</p></section>; return <section aria-label="persisted prompt context and contract" data-artifact-id={artifact.artifactId}>
  <h2 className="panel-title">prompt</h2><dl><dt>locked protocol</dt><dd>{artifact.protocol.id}@{artifact.protocol.version} · {artifact.protocol.hash}</dd><dt>rendered prompt hash</dt><dd>{artifact.promptHash}</dd><dt>model</dt><dd>{artifact.modelAlias}</dd><dt>cache hit rate</dt><dd>{artifact.cacheHitRate === null ? "unavailable" : `${artifact.cacheHitRate} recorded`}</dd></dl><h3>before override</h3><pre>{artifact.overrides.before || "none"}</pre><h3>after override</h3><pre>{artifact.overrides.after || "none"}</pre><h3>persisted redacted compiled preview</h3><pre>{artifact.compiledPreview}</pre><h3>lint results</h3>{artifact.lint.length === 0 ? <p className="state" data-state="verified">no recorded lint findings</p> : <ul>{artifact.lint.map((item) => <li className="state" data-state={item.severity === "error" ? "refuted" : "degraded"} key={item.code}>{item.severity} · {item.code} · {item.message}</li>)}</ul>}
  <h2 className="panel-title">context</h2><dl><dt>transfer policy</dt><dd>{artifact.context.policy}</dd><dt>trust</dt><dd className="state" data-state={artifact.context.trust === "untrusted" ? "tainted" : "verified"}>{artifact.context.trust}</dd><dt>included artifacts</dt><dd>{artifact.context.included.join(", ") || "none"}</dd><dt>excluded artifacts</dt><dd>{artifact.context.excluded.join(", ") || "none"}</dd><dt>token estimate</dt><dd>{artifact.context.tokenEstimate === null ? "unavailable" : `${artifact.context.tokenEstimate} estimated · ${artifact.context.estimateBasis ?? "basis unavailable"}`}</dd></dl>
  <h2 className="panel-title">output contract</h2><dl><dt>schema</dt><dd>{artifact.output.schema}</dd><dt>required fields</dt><dd>{artifact.output.requiredFields.join(", ")}</dd><dt>validation</dt><dd>{artifact.output.validationBehaviour}</dd><dt>structured-output tier</dt><dd className={artifact.output.tierDegradation === null ? undefined : "state"} data-state={artifact.output.tierDegradation === null ? undefined : "degraded"}>{artifact.output.structuredOutputTier}{artifact.output.tierDegradation === null ? "" : ` · degraded: ${artifact.output.tierDegradation}`}</dd></dl>
  <p className="state" data-state="tainted">provenance · persisted redacted artifact · never recompiled in browser</p>
  </section>; }

