import { runDeterministicLadder, type VerificationAttempt, type VerificationItem, type VerificationMethod, type VerificationOutcome, type VerificationTools } from "./ladder.js";

export const VERIFICATION_SUBGRAPH_NODE = Object.freeze({ kind: "subgraph" as const, purpose: "verification" as const });
export interface VerificationObjection { readonly citesLocation: boolean; readonly evidenceType: "repository" | "test" | "specification" | "inference" | "speculation"; readonly resolvedBy: string | null }
export interface VerificationIssue { readonly severity: VerificationItem["severity"]; readonly objections: readonly VerificationObjection[] }
export interface ModelVerificationRequest { readonly candidateId: string; readonly question: string; readonly context: { readonly claim: string; readonly citedContext: VerificationItem["citedContext"]; readonly deterministicAttempts: readonly { readonly method: VerificationAttempt["method"]; readonly artifactRefs: readonly string[]; readonly evidenceIds: readonly string[] }[] } }
export interface ModelVerificationResponse { readonly outcome: VerificationOutcome; readonly evidenceIds: readonly string[]; readonly artifactRefs: readonly string[]; readonly activityId: string; readonly confidence: number }
export interface VerificationModel { verify(request: ModelVerificationRequest): Promise<ModelVerificationResponse> }
export interface VerificationIssueOperation { readonly operationId: string; readonly candidateId: string; readonly authorId: "verification"; readonly round: number; readonly type: "accept" | "reject" | "needs_verification"; readonly citedEvidenceIds: readonly string[]; readonly reason: string; readonly verification: { readonly result: VerificationOutcome; readonly method: VerificationMethod; readonly evidenceIds: readonly string[]; readonly artifactRefs: readonly string[]; readonly toolCallIds: readonly string[]; readonly activityId: string; readonly confidence: number | null } }
export interface VerificationOperationSink { append(operation: VerificationIssueOperation): Promise<void> }
export interface VerificationResult { readonly candidateId: string; readonly outcome: VerificationOutcome; readonly method: VerificationMethod; readonly operation: VerificationIssueOperation; readonly attempts: readonly VerificationAttempt[]; readonly modelCalls: 0 | 1 }
export interface VerificationRunMetrics { readonly itemCount: number; readonly resolvedDisputes: number; readonly modelCalls: number; readonly deferredItemIds: readonly string[]; readonly rungDistribution: Readonly<Record<VerificationMethod, number>> }

export function escalateToVerification(issue: VerificationIssue): boolean { return (issue.severity === "critical" || issue.severity === "high") && issue.objections.some((objection) => objection.citesLocation && objection.evidenceType !== "speculation" && objection.resolvedBy === null); }

export async function verifyItem(item: VerificationItem, tools: VerificationTools, budget: { readonly allowModelCall: boolean }, dependencies: { readonly model?: VerificationModel; readonly sink: VerificationOperationSink; readonly round: number }): Promise<VerificationResult> {
  if (item.citedEvidenceIds.length === 0 || item.question.trim() === "" || item.question.includes("\n")) throw new Error("INVALID_VERIFICATION_ITEM");
  const ladder = await runDeterministicLadder(item, tools); let outcome: VerificationOutcome; let method: VerificationMethod; let evidenceIds: readonly string[]; let artifactRefs: readonly string[]; let toolCallIds: readonly string[]; let activityId: string; let confidence: number | null; let modelCalls: 0 | 1 = 0;
  if (ladder.resolved !== null) { outcome = ladder.resolved.verdict === "confirmed" ? "CONFIRMED" : "REJECTED"; method = ladder.resolved.method; evidenceIds = ladder.resolved.evidenceIds; artifactRefs = ladder.resolved.artifactRefs; toolCallIds = ladder.resolved.toolCallIds; activityId = ladder.resolved.activityId; confidence = ladder.resolved.confidence; }
  else if (budget.allowModelCall && dependencies.model !== undefined) {
    const response = await dependencies.model.verify(Object.freeze({ candidateId: item.candidateId, question: item.question, context: Object.freeze({ claim: item.claim, citedContext: item.citedContext, deterministicAttempts: Object.freeze(ladder.attempts.map(({ method: attemptedMethod, artifactRefs: refs, evidenceIds: ids }) => Object.freeze({ method: attemptedMethod, artifactRefs: refs, evidenceIds: ids }))) }) }));
    validateModelResponse(response); outcome = response.outcome; method = "single_model_question"; evidenceIds = response.evidenceIds; artifactRefs = response.artifactRefs; toolCallIds = Object.freeze([]); activityId = response.activityId; confidence = response.confidence; modelCalls = 1;
  } else { outcome = "STILL_NEEDS_VERIFICATION"; method = ladder.attempts.at(-1)?.method ?? "bounded_deterministic_check"; evidenceIds = item.citedEvidenceIds; artifactRefs = Object.freeze(ladder.attempts.flatMap(({ artifactRefs: refs }) => refs)); toolCallIds = Object.freeze(ladder.attempts.flatMap(({ toolCallIds: ids }) => ids)); activityId = ladder.attempts.at(-1)?.activityId ?? `verification:${item.candidateId}`; confidence = null; }
  const operation = operationFor(item, dependencies.round, outcome, method, evidenceIds.length === 0 ? item.citedEvidenceIds : evidenceIds, artifactRefs, toolCallIds, activityId, confidence); await dependencies.sink.append(operation);
  return Object.freeze({ candidateId: item.candidateId, outcome, method, operation, attempts: ladder.attempts, modelCalls });
}

export async function verifyItems(items: readonly VerificationItem[], tools: VerificationTools, config: { readonly maximumItems: number; readonly allowModelCall: boolean; readonly round: number }, dependencies: { readonly model?: VerificationModel; readonly sink: VerificationOperationSink }): Promise<{ readonly results: readonly VerificationResult[]; readonly metrics: VerificationRunMetrics }> {
  if (!Number.isSafeInteger(config.maximumItems) || config.maximumItems < 0) throw new Error("INVALID_VERIFICATION_ITEM_BUDGET"); const selected = items.slice(0, config.maximumItems); const deferred = items.slice(config.maximumItems).map(({ candidateId }) => candidateId); const results: VerificationResult[] = [];
  for (const item of selected) results.push(await verifyItem(item, tools, { allowModelCall: config.allowModelCall }, { ...dependencies, round: config.round }));
  const distribution = Object.fromEntries((["cited_lines", "symbol_or_call_path", "route_config_middleware", "dependency_or_import_path", "allowlisted_safe_test", "bounded_deterministic_check", "single_model_question"] as VerificationMethod[]).map((method) => [method, results.filter((result) => result.method === method).length])) as Record<VerificationMethod, number>;
  return Object.freeze({ results: Object.freeze(results), metrics: Object.freeze({ itemCount: results.length, resolvedDisputes: results.filter(({ outcome }) => outcome !== "STILL_NEEDS_VERIFICATION").length, modelCalls: results.reduce((sum, result) => sum + result.modelCalls, 0), deferredItemIds: Object.freeze(deferred), rungDistribution: Object.freeze(distribution) }) });
}

function operationFor(item: VerificationItem, round: number, outcome: VerificationOutcome, method: VerificationMethod, evidenceIds: readonly string[], artifactRefs: readonly string[], toolCallIds: readonly string[], activityId: string, confidence: number | null): VerificationIssueOperation { const type = outcome === "CONFIRMED" ? "accept" : outcome === "REJECTED" ? "reject" : "needs_verification"; return Object.freeze({ operationId: `verification:${round}:${item.candidateId}`, candidateId: item.candidateId, authorId: "verification", round, type, citedEvidenceIds: Object.freeze([...evidenceIds]), reason: `Verification ${outcome.toLocaleLowerCase("en-US")} via ${method}.`, verification: Object.freeze({ result: outcome, method, evidenceIds: Object.freeze([...evidenceIds]), artifactRefs: Object.freeze([...artifactRefs]), toolCallIds: Object.freeze([...toolCallIds]), activityId, confidence }) }); }
function validateModelResponse(response: ModelVerificationResponse): void { if (!["CONFIRMED", "REJECTED", "STILL_NEEDS_VERIFICATION"].includes(response.outcome) || response.activityId.trim() === "" || !Number.isFinite(response.confidence) || response.confidence < 0 || response.confidence > 1) throw new Error("INVALID_MODEL_VERIFICATION_RESPONSE"); }
