import type { PersistedFinding, PersistedIssue } from "../issue-board/model.js";
export type TraceLevel = "task" | "validation" | "issue" | "finding" | "evidence";
export interface TraceNode { readonly level: TraceLevel; readonly id: string; readonly label: string }
export interface PersistedPlanTask { readonly id: string; readonly title: string; readonly addresses: { readonly issues: readonly string[]; readonly validation: readonly string[]; readonly requirements: readonly string[] }; readonly routing: { readonly capability: string; readonly effort: string; readonly reason: readonly string[] }; readonly dependencies: { readonly dependsOn: readonly string[]; readonly blocks: readonly string[]; readonly conflictsWith: readonly string[] } }
export interface PersistedPlan { readonly id: string; readonly title: string; readonly mode: string; readonly acceptedIssueIds: readonly string[]; readonly validationContract: { readonly validation: readonly { readonly id: string; readonly assertion: string; readonly evidence: readonly string[] }[] }; readonly tasks: readonly PersistedPlanTask[]; readonly taskGraph: readonly { readonly from: string; readonly to: string }[]; readonly traceability: { readonly issueToValidation: readonly { readonly issueId: string; readonly validationIds: readonly string[] }[]; readonly requirementLinks: { readonly links: readonly { readonly requirementId: string; readonly validationIds: readonly string[]; readonly taskIds: readonly string[] }[] } }; readonly routingRecommendations: readonly { readonly taskId: string; readonly capability: string; readonly effort: string; readonly reason: readonly string[] }[]; readonly unresolvedQuestions: readonly { readonly id: string; readonly question: string; readonly blocking: boolean; readonly blastRadius: string }[]; readonly premiseReport: { readonly status: string; readonly interpretation: string; readonly limitations: readonly string[] } }
export interface PersistedCritique { readonly summary: string; readonly items: readonly { readonly id: string; readonly category: string; readonly blocking: boolean; readonly summary: string; readonly taskIds: readonly string[]; readonly issueIds: readonly string[] }[] }
export interface TraceGraph { readonly plan: PersistedPlan; readonly issues: readonly PersistedIssue[]; readonly findings: readonly PersistedFinding[] }
export const TRACE_CHAIN: readonly TraceLevel[] = Object.freeze(["task", "validation", "issue", "finding", "evidence"]);
export function forward({ plan, issues, findings }: TraceGraph, node: TraceNode): readonly TraceNode[] {
  if (node.level === "task") { const task = plan.tasks.find(({ id }) => id === node.id); return task === undefined ? [] : nodes("validation", task.addresses.validation, (id) => plan.validationContract.validation.find((entry) => entry.id === id)?.assertion ?? "assertion unavailable"); }
  if (node.level === "validation") { const linked = plan.traceability.issueToValidation.filter(({ validationIds }) => validationIds.includes(node.id)).map(({ issueId }) => issueId); return nodes("issue", linked, (id) => issues.find((issue) => issue.candidateId === id)?.claim.title ?? "canonical issue unavailable"); }
  if (node.level === "issue") { const issue = issues.find(({ candidateId }) => candidateId === node.id); return issue === undefined ? [] : nodes("finding", issue.sourceFindingIds, (id) => findings.find((finding) => finding.sourceFindingId === id)?.title ?? "source finding unavailable"); }
  if (node.level === "finding") { const finding = findings.find(({ sourceFindingId }) => sourceFindingId === node.id); return finding === undefined ? [] : Object.freeze(finding.evidence.map(({ id, text }) => Object.freeze({ level: "evidence" as const, id, label: text }))); }
  return [];
}
export function backward({ plan, issues, findings }: TraceGraph, node: TraceNode): readonly TraceNode[] {
  if (node.level === "evidence") { const owners = findings.filter(({ evidence }) => evidence.some(({ id }) => id === node.id)); return Object.freeze(owners.map(({ sourceFindingId, title }) => Object.freeze({ level: "finding" as const, id: sourceFindingId, label: title }))); }
  if (node.level === "finding") { const owners = issues.filter(({ sourceFindingIds }) => sourceFindingIds.includes(node.id)); return Object.freeze(owners.map(({ candidateId, claim }) => Object.freeze({ level: "issue" as const, id: candidateId, label: claim.title }))); }
  if (node.level === "issue") { const linked = plan.traceability.issueToValidation.filter(({ issueId }) => issueId === node.id).flatMap(({ validationIds }) => validationIds); return nodes("validation", linked, (id) => plan.validationContract.validation.find((entry) => entry.id === id)?.assertion ?? "assertion unavailable"); }
  if (node.level === "validation") { const owners = plan.tasks.filter(({ addresses }) => addresses.validation.includes(node.id)); return Object.freeze(owners.map(({ id, title }) => Object.freeze({ level: "task" as const, id, label: title }))); }
  return [];
}
function nodes(level: TraceLevel, ids: readonly string[], label: (id: string) => string): readonly TraceNode[] { return Object.freeze([...new Set(ids)].map((id) => Object.freeze({ level, id, label: label(id) }))); }
