import type { WorkflowJson } from "./layout.js";
const node = (id: string, kind: WorkflowJson["nodes"][number]["kind"], label: string): WorkflowJson["nodes"][number] => ({ id, kind, label });
const edges = (ids: readonly string[]): WorkflowJson["edges"] => ids.slice(1).map((id, index) => ({ id: `${ids[index]}-${id}`, from: ids[index]!, to: id }));
export const PRESET_WORKFLOWS: Readonly<Record<"audit-deep" | "diff-review" | "feature-simple" | "testing", WorkflowJson>> = Object.freeze({
  "audit-deep": { id: "audit-deep", nodes: [node("preflight", "deterministic", "Preflight"), node("auditor-a", "model", "Auditor A"), node("auditor-b", "model", "Auditor B"), node("auditor-c", "model", "Auditor C"), node("consensus", "loop", "Consensus"), node("verification", "subgraph", "Verification"), node("planner", "model", "Planner"), node("critic", "model", "Critic")], edges: [{ id: "p-a", from: "preflight", to: "auditor-a" }, { id: "p-b", from: "preflight", to: "auditor-b" }, { id: "p-c", from: "preflight", to: "auditor-c" }, { id: "a-c", from: "auditor-a", to: "consensus" }, { id: "b-c", from: "auditor-b", to: "consensus" }, { id: "c-c", from: "auditor-c", to: "consensus" }, ...edges(["consensus", "verification", "planner", "critic"]) ] },
  "diff-review": { id: "diff-review", nodes: [node("scope", "deterministic", "Diff scope"), node("auditor-a", "model", "Auditor A"), node("auditor-b", "model", "Auditor B"), node("disagreement", "gate", "Disagreement"), node("verification", "subgraph", "Verification")], edges: [{ id: "s-a", from: "scope", to: "auditor-a" }, { id: "s-b", from: "scope", to: "auditor-b" }, { id: "a-d", from: "auditor-a", to: "disagreement" }, { id: "b-d", from: "auditor-b", to: "disagreement" }, { id: "d-v", from: "disagreement", to: "verification" }] },
  "feature-simple": { id: "feature-simple", nodes: [node("requirements", "model", "Requirements"), node("risk", "gate", "Risk gate"), node("explore", "deterministic", "Targeted exploration"), node("planner", "model", "Planner"), node("render", "deterministic", "Render")], edges: edges(["requirements", "risk", "explore", "planner", "render"]) },
  testing: { id: "testing", nodes: [node("inventory", "deterministic", "Test inventory"), node("gaps", "model", "Risk gaps"), node("contract", "deterministic", "Validation contract"), node("planner", "model", "Test plan"), node("render", "deterministic", "Render")], edges: edges(["inventory", "gaps", "contract", "planner", "render"]) },
});

