export interface PremiseGroundTruthItem { readonly id: string; readonly kind: "defect" | "decoy"; readonly category: string; readonly path: string; readonly location: string; readonly detectionCriteria: string; readonly rationale: string }
export interface PremiseGroundTruth { readonly fixtureId: string; readonly version: number; readonly items: readonly PremiseGroundTruthItem[] }
export interface PremiseFinding { readonly findingId: string; readonly matchedGroundTruthIds: readonly string[] }
export interface PremiseAuditorRun { readonly auditorId: string; readonly modelIdentity: string; readonly independenceGroup: string; readonly findings: readonly PremiseFinding[]; readonly repairCount: number; readonly invalidEvidenceCount: number; readonly refusalCount: number; readonly cost: number; readonly latencyMs: number }
export interface PremiseCanonicalIssue { readonly issueId: string; readonly accepted: boolean; readonly matchedGroundTruthIds: readonly string[] }
export interface PremiseRun { readonly runId: string; readonly fixtureId: string; readonly protocolId: string; readonly protocolVersion: string; readonly currency: string; readonly mode: "scripted" | "real_models"; readonly auditors: readonly PremiseAuditorRun[]; readonly canonicalIssues: readonly PremiseCanonicalIssue[] }
export interface AuditorPremiseMetrics { readonly auditorId: string; readonly modelIdentity: string; readonly protocolIdentity: string; readonly independenceGroup: string; readonly findingCount: number; readonly trueFindingCount: number; readonly falsePositiveCount: number; readonly recall: number; readonly precision: number | null; readonly falsePositiveRate: number | null; readonly uniqueTrueContribution: number; readonly marginalTrueContribution: number; readonly marginalRecallGain: number; readonly repairFrequency: number | null; readonly invalidEvidenceRate: number | null; readonly refusalRate: number | null; readonly cost: number; readonly latencyMs: number }
export interface PremiseReport { readonly schemaVersion: 1; readonly runId: string; readonly fixtureId: string; readonly protocolIdentity: string; readonly mode: PremiseRun["mode"]; readonly currency: string; readonly groundTruth: { readonly defects: number; readonly decoys: number }; readonly auditors: readonly AuditorPremiseMetrics[]; readonly consensus: { readonly acceptedIssueCount: number; readonly trueAcceptedIssueCount: number; readonly falseAcceptedIssueCount: number; readonly precision: number | null; readonly recall: number; readonly costPerTrueAcceptedIssue: number | null }; readonly result: { readonly additionalAuditorUniqueContribution: readonly number[]; readonly premiseSignal: "positive" | "null" | "negative"; readonly interpretation: "smoke_test_only_not_proof" }; readonly limitations: readonly string[] }

export function scorePremiseRun(run: PremiseRun, groundTruth: PremiseGroundTruth): PremiseReport {
  if (run.fixtureId !== groundTruth.fixtureId) throw new Error("PREMISE_FIXTURE_ID_MISMATCH");
  if (run.protocolId.trim() === "" || run.protocolVersion.trim() === "" || run.currency.trim() === "") throw new Error("INVALID_PREMISE_RUN_IDENTITY");
  const truth = validateGroundTruth(groundTruth); const defects = new Set(truth.filter(({ kind }) => kind === "defect").map(({ id }) => id)); const known = new Set(truth.map(({ id }) => id));
  const auditorIds = new Set<string>(); const detectedBy = new Map<string, Set<string>>();
  for (const auditor of run.auditors) { if (auditorIds.has(auditor.auditorId) || auditor.modelIdentity.trim() === "" || auditor.independenceGroup.trim() === "") throw new Error("INVALID_PREMISE_AUDITOR_IDENTITY"); auditorIds.add(auditor.auditorId); for (const id of trueIds(auditor.findings, defects, known)) { const values = detectedBy.get(id) ?? new Set<string>(); values.add(auditor.auditorId); detectedBy.set(id, values); } }
  const seen = new Set<string>(); const protocolIdentity = `${run.protocolId}@${run.protocolVersion}`;
  const auditors = run.auditors.map((auditor): AuditorPremiseMetrics => {
    validateNonnegative(auditor); const trueFindings = auditor.findings.filter((finding) => matchingDefects(finding, defects, known).length > 0); const falsePositives = auditor.findings.length - trueFindings.length; const detected = trueIds(auditor.findings, defects, known); const marginal = [...detected].filter((id) => !seen.has(id)); for (const id of detected) seen.add(id);
    return Object.freeze({ auditorId: auditor.auditorId, modelIdentity: auditor.modelIdentity, protocolIdentity, independenceGroup: auditor.independenceGroup, findingCount: auditor.findings.length, trueFindingCount: trueFindings.length, falsePositiveCount: falsePositives, recall: ratio(detected.size, defects.size) ?? 0, precision: ratio(trueFindings.length, auditor.findings.length), falsePositiveRate: ratio(falsePositives, auditor.findings.length), uniqueTrueContribution: [...detected].filter((id) => detectedBy.get(id)?.size === 1).length, marginalTrueContribution: marginal.length, marginalRecallGain: ratio(marginal.length, defects.size) ?? 0, repairFrequency: ratio(auditor.repairCount, auditor.findings.length), invalidEvidenceRate: ratio(auditor.invalidEvidenceCount, auditor.findings.length), refusalRate: ratio(auditor.refusalCount, auditor.findings.length), cost: auditor.cost, latencyMs: auditor.latencyMs });
  });
  const accepted = run.canonicalIssues.filter(({ accepted: value }) => value); const trueAccepted = accepted.filter((issue) => matchingDefects(issue, defects, known).length > 0); const acceptedDefects = new Set(trueAccepted.flatMap((issue) => matchingDefects(issue, defects, known))); const totalCost = run.auditors.reduce((sum, { cost }) => sum + cost, 0);
  const laterContribution = auditors.slice(1).map(({ uniqueTrueContribution }) => uniqueTrueContribution); const premiseSignal = laterContribution.some((value) => value > 0) ? "positive" : auditors.slice(1).some(({ falsePositiveCount }) => falsePositiveCount > 0) ? "negative" : "null";
  return Object.freeze({ schemaVersion: 1, runId: run.runId, fixtureId: run.fixtureId, protocolIdentity, mode: run.mode, currency: run.currency, groundTruth: Object.freeze({ defects: defects.size, decoys: truth.length - defects.size }), auditors: Object.freeze(auditors), consensus: Object.freeze({ acceptedIssueCount: accepted.length, trueAcceptedIssueCount: trueAccepted.length, falseAcceptedIssueCount: accepted.length - trueAccepted.length, precision: ratio(trueAccepted.length, accepted.length), recall: ratio(acceptedDefects.size, defects.size) ?? 0, costPerTrueAcceptedIssue: acceptedDefects.size === 0 ? null : round(totalCost / acceptedDefects.size) }), result: Object.freeze({ additionalAuditorUniqueContribution: Object.freeze(laterContribution), premiseSignal, interpretation: "smoke_test_only_not_proof" as const }), limitations: Object.freeze(["One small fixture cannot prove or disprove the multi-auditor premise.", run.mode === "scripted" ? "Scripted auditors test deterministic measurement and orchestration, not real-model intelligence." : "Real-model results are specific to the recorded protocol and model identities.", "Tool quality, scope selection, clustering and validation can affect observed recall."]) });
}

export function realPremiseMeasurementEnabled(environment: Readonly<Record<string, string | undefined>>): boolean { return environment["ARBITRA_PREMISE_REAL_MODELS"] === "1" && ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "GOOGLE_API_KEY"].some((key) => (environment[key]?.length ?? 0) > 0); }
function validateGroundTruth(groundTruth: PremiseGroundTruth): readonly PremiseGroundTruthItem[] { const ids = new Set<string>(); if (groundTruth.items.length === 0) throw new Error("EMPTY_PREMISE_GROUND_TRUTH"); for (const item of groundTruth.items) { if (ids.has(item.id) || item.path.trim() === "" || item.location.trim() === "" || item.detectionCriteria.trim() === "" || item.rationale.trim() === "") throw new Error(`INVALID_PREMISE_GROUND_TRUTH:${item.id}`); ids.add(item.id); } return groundTruth.items; }
function matchingDefects(value: { readonly matchedGroundTruthIds: readonly string[] }, defects: ReadonlySet<string>, known: ReadonlySet<string>): string[] { for (const id of value.matchedGroundTruthIds) if (!known.has(id)) throw new Error(`UNKNOWN_PREMISE_GROUND_TRUTH_ID:${id}`); return [...new Set(value.matchedGroundTruthIds.filter((id) => defects.has(id)))]; }
function trueIds(findings: readonly PremiseFinding[], defects: ReadonlySet<string>, known: ReadonlySet<string>): Set<string> { return new Set(findings.flatMap((finding) => matchingDefects(finding, defects, known))); }
function validateNonnegative(auditor: PremiseAuditorRun): void { for (const value of [auditor.repairCount, auditor.invalidEvidenceCount, auditor.refusalCount, auditor.cost, auditor.latencyMs]) if (!Number.isFinite(value) || value < 0) throw new Error(`INVALID_PREMISE_AUDITOR_METRIC:${auditor.auditorId}`); }
function ratio(numerator: number, denominator: number): number | null { return denominator === 0 ? null : round(numerator / denominator); }
function round(value: number): number { return Math.round(value * 10_000) / 10_000; }
