// @vitest-environment jsdom
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { ArtifactApi } from "../../src/api/artifacts.js";
import { RunApi, useRehydratedRun } from "../../src/api/runs.js";
import { InspectorView, type InspectorSelection } from "../../src/columns/inspector/InspectorView.js";
import { PromptView, type PersistedPromptArtifact } from "../../src/columns/prompt/PromptView.js";
import { ArtifactView } from "../../src/controls/ArtifactView.js";
import { InspectorOverlay, RunControls } from "../../src/controls/RunControls.js";

afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
const prompt: PersistedPromptArtifact = { artifactId: "artifact:prompt-a", redacted: true, nodeId: "auditor-a", modelAlias: "reviewer-a", protocol: { id: "production-audit", version: "1.0.0", hash: "abc123", locked: true }, overrides: { before: "bounded before", after: "bounded after" }, compiledPreview: "[REDACTED:api_key] persisted prompt", promptHash: "prompt-hash-a", lint: [{ code: "OVER_PROMPTING", severity: "warning", message: "Use plain language." }], context: { policy: "selected_artifacts", trust: "untrusted", included: ["project-context.json"], excluded: ["raw-audit-transcripts"], tokenEstimate: 4200, estimateBasis: "canonical bytes" }, output: { schema: "SourceFindingIR", requiredFields: ["id", "evidence"], validationBehaviour: "repair_once", structuredOutputTier: "provider_native", tierDegradation: "strict schema unsupported" }, cacheHitRate: 0.75 };

describe("persisted prompt, context and output contract", () => {
  it("shows an auditor's exact prompt hash, lint, provenance, estimate basis and tier degradation", () => { render(<PromptView selection={{ kind: "model", artifact: prompt }} />); for (const text of ["prompt-hash-a", "OVER_PROMPTING", "persisted redacted compiled preview", "selected_artifacts", "untrusted", "4200 estimated · canonical bytes", "SourceFindingIR", "strict schema unsupported", "0.75 recorded", "never recompiled in browser"]) expect(screen.getByText(new RegExp(text, "i"))).toBeTruthy(); expect(screen.getByText(/strict schema unsupported/i).closest("dd")?.dataset.state).toBe("degraded"); });
  it("shows deterministic transformation configuration instead of an empty or reconstructed prompt", () => { render(<PromptView selection={{ kind: "deterministic", nodeId: "cluster", transformation: { strategy: "exact-signals", escalatedPairs: 4 } }} />); expect(screen.getByText("deterministic transformation")).toBeTruthy(); expect(screen.getByText(/exact-signals/)).toBeTruthy(); expect(screen.queryByText("persisted redacted compiled preview")).toBeNull(); });
  it("never imports compiler code into the prompt view", () => { const source = readFileSync(resolve(process.cwd(), "src/columns/prompt/PromptView.tsx"), "utf8"); expect(source).not.toMatch(/compilePrompt|prompt\/compiler|canonicalSerial/iu); expect(source).toContain("artifact.compiledPreview"); });
  it("switches between per-auditor persisted hashes without sharing a reconstructed prompt", () => { const rendered = render(<PromptView selection={{ kind: "model", artifact: prompt }} />); expect(screen.getByText("prompt-hash-a")).toBeTruthy(); rendered.rerender(<PromptView selection={{ kind: "model", artifact: { ...prompt, artifactId: "artifact:prompt-b", nodeId: "auditor-b", modelAlias: "reviewer-b", promptHash: "prompt-hash-b", compiledPreview: "persisted B" } }} />); expect(screen.getByText("prompt-hash-b")).toBeTruthy(); expect(screen.queryByText("prompt-hash-a")).toBeNull(); expect(screen.getByText("persisted B")).toBeTruthy(); });
  it("has no hidden-reasoning presentation path", () => { const sources = ["src/columns/prompt/PromptView.tsx", "src/columns/inspector/InspectorView.tsx", "src/controls/ArtifactView.tsx"].map((path) => readFileSync(resolve(process.cwd(), path), "utf8")).join("\n"); expect(sources).not.toMatch(/chain.?of.?thought|hiddenReasoning|reasoningContent/iu); });
});

describe("contextual inspector", () => {
  const variants: readonly InspectorSelection[] = [
    { kind: "audit", scope: "diff", depth: "deep", categories: ["security"], consensusPolicy: "risk_weighted", rounds: 2, tools: ["repo.readFile"], securityOverlapBudget: 8 },
    { kind: "model", model: "reviewer-a", effort: "xhigh", effortCollapse: "xhigh→high", budget: "$4", fallback: "reviewer-b", tools: ["repo.readFile"], outputLimit: 4096, structuredTierDegradation: "strict→json_mode" },
    { kind: "planner", taskGranularity: "behavioural", routingThresholds: "14 dimensions", criticPolicy: "conditional", validationRules: ["every task maps"] },
    { kind: "workflow", repository: "fixture", snapshot: "sha256:snapshot", base: "main", head: "HEAD", budgets: "$20", concurrency: 4, retries: 2, outputLocations: ["implementation/"], exclusions: [".runs/"], secretSettings: "environment references", protocolVersion: "1.0.0", runState: "BLOCKED", telemetry: "local" },
  ];
  for (const selection of variants) it(`renders only the ${selection.kind} field set`, () => { render(<InspectorView selection={selection} />); expect(screen.getByLabelText(`${selection.kind} inspector`)).toBeTruthy(); expect(screen.getByText(`${selection.kind} inspector`)).toBeTruthy(); });
  it("keeps collapse and structured-tier degradation as labelled non-colour states", () => { render(<InspectorView selection={variants[1]!} />); expect(screen.getByText("xhigh→high").dataset.state).toBe("degraded"); expect(screen.getByText("strict→json_mode").dataset.state).toBe("degraded"); });
});

describe("run controls, reconnect and persisted artifacts", () => {
  it("maps every TASK-044 lifecycle method exactly and rejects every non-success response", async () => { const calls: string[] = []; vi.stubGlobal("fetch", async (input: RequestInfo | URL, init?: RequestInit) => { calls.push(`${init?.method ?? "GET"} ${String(input)}`); return json({ runId: "run-1", state: "CREATED", resumable: true, checkpoints: [], accepted: true, estimate: {}, gate: "clear" }); }); const api = new RunApi(); await api.selectRepository("fixture"); await api.estimate("cfg-1", "fixture"); await api.start("cfg-1", "fixture"); await api.status("run-1"); await api.resume("run-1"); await api.cancel("run-1"); await api.respondCheckpoint("run-1", "cp-1", "continue"); expect(calls).toEqual(["POST /repositories/select", "POST /estimate", "POST /runs", "GET /runs/run-1", "POST /runs/run-1/resume", "POST /runs/run-1/cancel", "POST /runs/run-1/checkpoints/cp-1"]); vi.stubGlobal("fetch", async () => json({}, 503)); for (const operation of [() => api.selectRepository("fixture"), () => api.estimate("cfg-1", "fixture"), () => api.start("cfg-1", "fixture"), () => api.status("run-1"), () => api.resume("run-1"), () => api.cancel("run-1"), () => api.respondCheckpoint("run-1", "cp-1", "continue")]) await expect(operation()).rejects.toThrow("RUN_API_503"); });
  it("maps every control to the declared route and rehydrates a waiting checkpoint before answering it", async () => { const calls: string[] = []; let statusCalls = 0; vi.stubGlobal("fetch", async (input: RequestInfo | URL, init?: RequestInit) => { const path = String(input); calls.push(`${init?.method ?? "GET"} ${path}`); if (path === "/runs/run-1") { statusCalls += 1; return json({ runId: "run-1", state: statusCalls === 1 ? "BLOCKED" : "PLANNING", resumable: true, checkpoints: statusCalls === 1 ? [{ id: "cp-1", stage: "before_planning", status: "pending", prompt: "Proceed?" }] : [] }); } if (path.endsWith("/checkpoints/cp-1")) return json({ accepted: true }); if (path === "/repositories/select") return json({ root: "fixture" }); if (path === "/estimate") return json({ estimate: { calls: 2 }, gate: "clear" }); if (path === "/runs" && init?.method === "POST") return json({ runId: "run-1", state: "CREATED", resumable: true, checkpoints: [] }); if (path.endsWith("/resume")) return json({ runId: "run-1", state: "CREATED", resumable: true, checkpoints: [] }); if (path.endsWith("/cancel")) return json({ runId: "run-1", state: "CANCELLED", resumable: true, checkpoints: [] }); return json({}, 404); }); const api = new RunApi(); render(<RunControls api={api} configurationId="cfg-1" initialRunId="run-1" />); expect(await screen.findByText(/before_planning · Proceed/)).toBeTruthy(); fireEvent.click(screen.getByText("continue")); await waitFor(() => expect(screen.getByText(/PLANNING/)).toBeTruthy()); const repository = screen.getByLabelText("repository"); fireEvent.change(repository, { target: { value: "fixture" } }); fireEvent.click(screen.getByText("select")); fireEvent.click(screen.getByText("estimate")); fireEvent.click(screen.getByText("resume")); fireEvent.click(screen.getByText("cancel")); await waitFor(() => expect(calls).toEqual(expect.arrayContaining(["GET /runs/run-1", "POST /runs/run-1/checkpoints/cp-1", "POST /repositories/select", "POST /estimate", "POST /runs/run-1/resume", "POST /runs/run-1/cancel"]))); });
  it("rehydrates authoritative status before opening the SSE delta stream", async () => { const order: string[] = []; const api = new RunApi(); vi.spyOn(api, "status").mockImplementation(async () => { order.push("status"); return { runId: "run-1", state: "BLOCKED", resumable: true, checkpoints: [] }; }); class Source { onmessage: ((event: MessageEvent) => void) | null = null; constructor() { order.push("sse"); } close() {} } vi.stubGlobal("EventSource", Source); function Fixture() { const run = useRehydratedRun(api, "run-1"); return <div>{run.resource?.state ?? "loading"}</div>; } render(<Fixture />); expect(await screen.findByText("BLOCKED")).toBeTruthy(); expect(order).toEqual(["status", "sse"]); });
  it("surfaces a labelled error state for lifecycle failures", async () => { vi.stubGlobal("fetch", async () => json({ error: "offline" }, 503)); render(<RunControls api={new RunApi()} configurationId="cfg-1" />); fireEvent.change(screen.getByLabelText("repository"), { target: { value: "fixture" } }); fireEvent.click(screen.getByText("select")); expect(await screen.findByText("RUN_API_503")).toBeTruthy(); expect(screen.getByText("RUN_API_503").dataset.state).toBe("degraded"); });
  it("loads bounded redacted persisted content and exposes truncation plus continuation", async () => { vi.stubGlobal("fetch", async () => json({ artifactId: "a-1", kind: "compiled-prompt", mediaType: "text/plain", bytes: 512, redacted: true, content: "[REDACTED:api_key]", truncated: true, continuationArtifactId: "a-2" })); render(<ArtifactView api={new ArtifactApi()} runId="run-1" artifactId="a-1" />); expect(await screen.findByText("[REDACTED:api_key]")).toBeTruthy(); expect(screen.getByText(/truncated · continuation artifact a-2/).dataset.state).toBe("unexamined"); });
  it("gives the responsive inspector overlay first focus, keyboard dismissal and intact run controls", async () => { const dismiss = vi.fn(); render(<InspectorOverlay open title="run inspector" onDismiss={dismiss}><RunControls api={new RunApi()} configurationId="cfg-1" /></InspectorOverlay>); const close = screen.getByText("close inspector"); await waitFor(() => expect(document.activeElement).toBe(close)); expect(screen.getByText("run controls")).toBeTruthy(); fireEvent.keyDown(document, { key: "Escape" }); expect(dismiss).toHaveBeenCalledTimes(1); });
  it("retains text and structural marks in forced-colour mode", () => { const css = ["src/columns/prompt/prompt.css", "src/controls/run-controls.css"].map((path) => readFileSync(resolve(process.cwd(), path), "utf8")).join("\n"); expect(css.match(/@media \(forced-colors: active\)/gu)).toHaveLength(2); expect(css).toContain("border-color: CanvasText"); render(<PromptView selection={{ kind: "model", artifact: null }} />); expect(screen.getByText("persisted prompt artifact unavailable").dataset.state).toBe("unexamined"); });
});

function json(value: unknown, status = 200): Response { return new Response(JSON.stringify(value), { status, headers: { "content-type": "application/json" } }); }
